---
    - hosts: winsvr
      gather_facts: false

      tasks:
        - name: Configure IE proxy settings to apply per user
          win_regedit:
            path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\CurrentVersion\Internet Settings
            name: ProxySettingsPerUser
            data: 1
            type: dword
            state: present

        #- name: Set credential to use for proxy auth
        #  win_credential:
        #    name: ansible.proxy  # The name should be the FQDN of the proxy host
        #    type: generic_password
        #    username: proxyuser
        #    secret: proxypass
        #    state: present
        #become: yes
        #become_user: '{{ ansible_user }}'
        #become_method: runas

        - name: Remove
          win_inet_proxy:
            proxy: ''
            bypass: ''
...