---
    - hosts: winsvr
      gather_facts: false
      
      tasks:
        - name: "パスワードポリシーを変更する。パスワードの最小の長さ0以上"
          win_security_policy:
            section: System Access
            key: MinimumPasswordLength
            value: 0

        - name: "パスワードポリシーを変更する。パスワードの複雑さ要件を無効"
          win_security_policy:
            section: System Access
            key: PasswordComplexity
            value: 0

        - name: "パスワードポリシーを変更する。パスワードの有効期限を無期限"
          win_security_policy:
            section: System Access
            key: MaximumPasswordAge
            value: -1
...
