---
    - name: Windows Update by Ansible
      hosts: winsvr
      gather_facts: false

      vars:
        remote_logfile_path: C:\tmp\win_update_log_{{ inventory_hostname }}.log
        local_logfile_path: /tmp/ansible_logs/

      tasks:
        - name: Do Windows Update
          win_updates:
            category_names:
              - Application
              - CriticalUpdates
              - DefinitionUpdates
              - SecurityUpdates
              - UpdateRollups
              - Updates
            log_path: "{{ remote_logfile_path }}"
            server_selection: windows_update
            state: installed
          register: update_result

        - name: Debug display update results
          debug:
            var: update_result
            verbosity: 0

        - name: reboot if needed
          win_reboot:
          when: update_result.reboot_required

        - name: Get a win_update log file from a remote Windows server.
          fetch: 
            src: "{{ remote_logfile_path }}"
            dest: "{{ local_logfile_path }}"
            flat: yes
...